"use client";

import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { Minus, Plus, RotateCcw } from "lucide-react";

export function ImageCropDialog({ file, purpose, onCancel, onApply }: { file: File; purpose: "avatar" | "cover"; onCancel: () => void; onApply: (file: File) => Promise<void> }) {
  const url = useMemo(() => URL.createObjectURL(file), [file]); const frame = useRef<HTMLDivElement>(null); const drag = useRef<{ x: number; y: number; px: number; py: number } | null>(null); const [ratio, setRatio] = useState(1); const [size, setSize] = useState({ width: 0, height: 0 }); const [zoom, setZoom] = useState(1); const [x, setX] = useState(0); const [y, setY] = useState(0); const [saving, setSaving] = useState(false); const aspect = purpose === "avatar" ? 1 : 3;
  const baseWidth = ratio >= aspect ? 100 * ratio / aspect : 100; const baseHeight = ratio >= aspect ? 100 : 100 * aspect / ratio; const maxX = Math.max(0, (baseWidth * zoom - 100) / 2); const maxY = Math.max(0, (baseHeight * zoom - 100) / 2); const width = size.width * baseWidth * zoom / 100; const height = size.height * baseHeight * zoom / 100;
  useEffect(() => () => URL.revokeObjectURL(url), [url]); const clamp = (v: number, max: number) => Math.max(-max, Math.min(max, v));
  const move = (event: ReactPointerEvent<HTMLDivElement>) => { if (!drag.current || !frame.current) return; const box = frame.current.getBoundingClientRect(); setX(clamp(drag.current.x + (event.clientX - drag.current.px) / box.width * 100, maxX)); setY(clamp(drag.current.y + (event.clientY - drag.current.py) / box.height * 100, maxY)); };
  const apply = async () => { setSaving(true); try { const image = new Image(); image.src = url; await image.decode(); const h = 1000; const w = Math.round(h * aspect); const scale = Math.max(w / image.naturalWidth, h / image.naturalHeight) * zoom; const dw = image.naturalWidth * scale; const dh = image.naturalHeight * scale; const canvas = document.createElement("canvas"); canvas.width = w; canvas.height = h; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.drawImage(image, (w - dw) / 2 + x * w / 100, (h - dh) / 2 + y * h / 100, dw, dh); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/jpeg", .92)); if (blob) await onApply(new File([blob], `${purpose}-${Date.now()}.jpg`, { type: "image/jpeg" })); } finally { setSaving(false); } };
  const imgStyle = { width: `${width}px`, height: `${height}px`, left: `calc(50% + ${x * size.width / 100}px)`, top: `calc(50% + ${y * size.height / 100}px)`, transform: "translate(-50%, -50%)" };
  return <div role="dialog" aria-modal="true" aria-label="ویرایش رسانه" className="fixed inset-0 z-[60] bg-solid-dark/85 sm:flex sm:items-center sm:justify-center sm:p-5"><div className="mx-auto flex h-dvh w-full max-w-md flex-col overflow-hidden bg-[#eef5f8] sm:h-[min(820px,90dvh)] sm:rounded-2xl"><header className="flex h-14 shrink-0 items-center justify-between bg-surface px-4 text-foreground"><button type="button" onClick={onCancel} className="min-h-10 text-xs font-bold">بازگشت</button><h2 className="text-sm font-black">ویرایش رسانه</h2><button type="button" disabled={saving} onClick={() => void apply()} className="min-h-9 rounded-pill bg-foreground px-4 text-xs font-black text-background">{saving ? "در حال آماده‌سازی…" : "اعمال"}</button></header><div className="relative flex min-h-0 flex-1 items-center justify-center overflow-hidden p-5"><img src={url} alt="" aria-hidden="true" className="pointer-events-none absolute max-w-none opacity-25" style={imgStyle} /><div ref={frame} className={`relative touch-none overflow-hidden border-4 border-info shadow-lg ${purpose === "avatar" ? "h-72 w-72 rounded-full" : "aspect-[3/1] w-full rounded-sm"}`} onPointerDown={(event) => { drag.current = { x, y, px: event.clientX, py: event.clientY }; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={move} onPointerUp={(event) => { drag.current = null; event.currentTarget.releasePointerCapture(event.pointerId); }} onPointerCancel={() => { drag.current = null; }}><img src={url} alt="برای جابه‌جایی تصویر، آن را بکشید" draggable={false} onLoad={(event) => { setRatio(event.currentTarget.naturalWidth / event.currentTarget.naturalHeight); const box = frame.current?.getBoundingClientRect(); if (box) setSize({ width: box.width, height: box.height }); }} className="absolute max-w-none select-none" style={imgStyle} /></div></div><div className="shrink-0 border-t border-divider bg-surface px-5 py-5"><p className="mb-3 text-center text-xs text-foreground-subtle">برای جابه‌جایی، تصویر را بکشید.</p><div className="flex items-center gap-3"><Minus className="h-4 w-4 text-icon-muted" /><input aria-label="بزرگ‌نمایی" type="range" min="1" max="3" step=".05" value={zoom} onChange={(event) => { const next = Number(event.target.value); setZoom(next); setX((value) => clamp(value, Math.max(0, (baseWidth * next - 100) / 2))); setY((value) => clamp(value, Math.max(0, (baseHeight * next - 100) / 2))); }} className="w-full accent-info" /><Plus className="h-4 w-4 text-icon-muted" /></div><button type="button" onClick={() => { setZoom(1); setX(0); setY(0); }} className="mx-auto mt-4 inline-flex min-h-9 items-center gap-2 text-xs font-bold text-foreground-secondary"><RotateCcw className="h-4 w-4" />بازنشانی</button></div></div></div>;
}
