import Link from "next/link";
import type { Route } from "next";
import { Heart, MessageCircle, Repeat2, Share2 } from "lucide-react";
import type { ProfileActivity as ProfileActivityModel } from "../types";

type ProfileActivityProps = { activity: ProfileActivityModel; liked: boolean; reposted: boolean; onLike: () => void; onRepost: () => void; };

export function ProfileActivity({ activity, liked, reposted, onLike, onRepost }: ProfileActivityProps) {
  return <section className="space-y-3 px-4"><h2 className="text-xs font-bold text-slate-950 dark:text-white">روایت‌های ثبت‌شده این پایگاه</h2><article className="rounded-xl border border-slate-200 p-3 dark:border-slate-800"><div className="flex justify-between text-[10px] text-slate-400"><span className="inline-flex items-center gap-1 font-bold text-slate-900 dark:text-white"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />{activity.authorLabel}</span><span>{activity.timeLabel}</span></div><Link href={("/posts/" + activity.id) as Route} className="mt-3 block text-xs leading-7 text-slate-700 transition hover:text-brand-red dark:text-slate-200">«{activity.content}»</Link><div className="mt-3 grid grid-cols-3 gap-1">{activity.tags.map((tag) => <span key={tag} className="rounded bg-slate-100 p-1.5 text-center text-[9px] text-slate-700 dark:bg-slate-900 dark:text-slate-300">{tag}</span>)}</div><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-2 text-xs text-slate-400 dark:border-slate-800"><button type="button" onClick={onLike} className={"inline-flex items-center gap-1 hover:text-brand-red " + (liked ? "text-brand-red" : "")}><Heart className={"h-3.5 w-3.5 " + (liked ? "fill-current" : "")} />{activity.likes + (liked ? 1 : 0)}</button><button type="button" onClick={onRepost} className={"inline-flex items-center gap-1 hover:text-emerald-500 " + (reposted ? "text-emerald-500" : "")}><Repeat2 className="h-3.5 w-3.5" />{activity.reposts}</button><Link href={("/posts/" + activity.id) as Route} className="inline-flex items-center gap-1 hover:text-blue-500"><MessageCircle className="h-3.5 w-3.5" />{activity.comments}</Link><button type="button" aria-label="اشتراک‌گذاری" className="hover:text-amber-500"><Share2 className="h-3.5 w-3.5" /></button></div></article></section>;
}
