import { BadgeCheck, ChevronDown, Clock3 } from "lucide-react";
import type { ProfileDetails, ProfileSection, ProfileTab } from "../types";

type ProfileInfoProps = { profile: ProfileDetails; tab: ProfileTab; expandedSections: Set<ProfileSection>; onToggleSection: (section: ProfileSection) => void; };

function Stats({ items }: { items: ProfileDetails["squareStats"] }) {
  return <div className="grid grid-cols-3 gap-2 border-y border-slate-200 py-3 text-center text-xs dark:border-slate-800">{items.map((item) => <div key={item.label}><strong className={"block text-sm font-black " + (item.tone === "success" ? "text-emerald-500" : "text-slate-950 dark:text-white")}>{item.value}</strong><span className="mt-1 block text-[10px] text-slate-400">{item.label}</span></div>)}</div>;
}

export function ProfileInfo({ profile, tab, expandedSections, onToggleSection }: ProfileInfoProps) {
  if (tab === "resume") return <section className="space-y-3 px-4"><div><h2 className="flex items-center gap-1.5 text-base font-black text-slate-950 dark:text-white">محمدصادق رضایی<span className="rounded border border-emerald-500/30 bg-emerald-500/10 px-1.5 py-0.5 text-[10px] text-emerald-600 dark:text-emerald-400">عضو فعال تبیین</span></h2><p className="mt-1 text-xs text-slate-500">کارشناس ارشد علوم سیاسی | فعال رسانه و میدان</p><p className="mt-1 text-[11px] text-slate-400">{profile.identity.location}</p></div><Stats items={profile.resumeStats} /><div className="space-y-2">{(["about", "skills"] as ProfileSection[]).map((section) => { const open = expandedSections.has(section); const title = section === "about" ? "خلاصه سوابق و درباره من" : "مهارت‌ها و نشان‌های تخصصی"; return <div key={section} className="overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-800"><button type="button" onClick={() => onToggleSection(section)} className="flex w-full items-center justify-between bg-slate-50 p-3.5 text-xs font-bold text-slate-900 dark:bg-slate-900/60 dark:text-white"><span>{title}</span><ChevronDown className={"h-4 w-4 transition-transform " + (open ? "rotate-180" : "")} /></button>{open ? <div className="border-t border-slate-100 bg-white p-3.5 text-[11px] leading-7 text-slate-600 dark:border-slate-800/80 dark:bg-[#070a0f] dark:text-slate-300">{section === "about" ? profile.about : <div className="flex flex-wrap gap-2">{profile.skills.map((skill) => <span key={skill} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-1.5 dark:border-slate-800 dark:bg-slate-900">{skill}</span>)}</div>}</div> : null}</div>; })}</div></section>;

  return <section className="space-y-3 px-4"><div className="flex items-start justify-between"><div><h2 className="flex items-center gap-1.5 text-base font-black text-slate-950 dark:text-white">{profile.identity.name}<BadgeCheck className="h-4 w-4 fill-blue-500 text-white" /></h2><p className="mt-1 text-xs text-slate-400"><span dir="ltr">@{profile.identity.handle}</span> · {profile.identity.subtitle}</p></div></div><Stats items={profile.squareStats} /><div className="rounded-2xl border border-slate-200 p-3.5 dark:border-slate-800"><h3 className="flex items-center gap-1.5 text-sm font-bold text-slate-950 dark:text-white"><Clock3 className="h-4 w-4 text-brand-red" />جدول امشب میدان</h3><div className="mt-3 space-y-1.5">{profile.schedule.map((item) => <div key={item.id} className={"flex items-center justify-between border-b border-slate-100 py-1.5 text-xs last:border-b-0 dark:border-slate-800/60 " + (item.highlighted ? "font-bold text-amber-600 dark:text-amber-400" : "text-slate-700 dark:text-slate-300")}><span>{item.title}</span><span className="font-mono text-slate-500 dark:text-slate-400">{item.time}</span></div>)}</div></div></section>;
}