"use client";

import { useMemo, useState } from "react";
import { CalendarDays, Save } from "lucide-react";
import { PersianDatePicker, tehranTodayIso } from "@/components/shared/PersianDatePicker";
import { AdminField, fieldClass } from "./AdminField";
import { AdminPageHeader } from "./AdminPageHeader";
import { adminErrorMessage } from "../services/admin-api";
import { type AdminReportDay, type ReportDayInput, updateReportDay } from "../services/report-days.service";

const empty: ReportDayInput = { title: "", subtitle: "", description: "", textColor: "", backgroundColor: "" };

export function AdminReportDaysView({ initial }: { initial: AdminReportDay[] }) {
  const [days, setDays] = useState(initial); const [date, setDate] = useState(tehranTodayIso());
  const [draft, setDraft] = useState<ReportDayInput>(() => { const current = initial.find((item) => item.date === tehranTodayIso()); return current ? { title: current.title, subtitle: current.subtitle, description: current.description, textColor: current.textColor, backgroundColor: current.backgroundColor } : empty; });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const selected = useMemo(() => days.find((item) => item.date === date), [days, date]);
  const select = (next: string) => { setDate(next); const current = days.find((item) => item.date === next); setDraft(current ? { title: current.title, subtitle: current.subtitle, description: current.description, textColor: current.textColor, backgroundColor: current.backgroundColor } : empty); setMessage(""); };
  const save = async () => { setBusy(true); setMessage(""); try { const saved = await updateReportDay(date, draft); setDays((current) => current.map((item) => item.date === date ? saved : item)); setDraft({ title: saved.title, subtitle: saved.subtitle, description: saved.description, textColor: saved.textColor, backgroundColor: saved.backgroundColor }); setMessage("تنظیمات این روز ذخیره شد."); } catch (error) { setMessage(adminErrorMessage(error, "ذخیره تنظیمات روز ممکن نشد.")); } finally { setBusy(false); } };
  return <div className="min-h-full bg-background" dir="rtl"><AdminPageHeader title="گزارش" description="عنوان، متن و رنگ کارت روزهای تجمع را مدیریت کنید." crumbs={[{ label: "گزارش" }]} limitation="روزهای دارای گزارش یا عنوان در روزشمار عمومی نمایش داده می‌شوند." />
    <div className="grid gap-4 p-3 sm:p-4 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-card border border-border bg-surface p-4"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-brand" /><h2 className="text-sm font-black">تنظیمات روز</h2></div><div className="mt-4"><PersianDatePicker value={date} onChange={select} allow="past" ariaLabel="انتخاب روز گزارش" /></div>
      <div className="mt-4 grid gap-4"><AdminField label="عنوان" htmlFor="report-day-title"><input id="report-day-title" value={draft.title} onChange={(event) => setDraft((value) => ({ ...value, title: event.target.value }))} className={fieldClass} /></AdminField><AdminField label="زیرعنوان" htmlFor="report-day-subtitle"><input id="report-day-subtitle" value={draft.subtitle} onChange={(event) => setDraft((value) => ({ ...value, subtitle: event.target.value }))} className={fieldClass} /></AdminField><AdminField label="توضیح کوتاه" htmlFor="report-day-description"><textarea id="report-day-description" value={draft.description} onChange={(event) => setDraft((value) => ({ ...value, description: event.target.value }))} className={`${fieldClass} min-h-24`} /></AdminField><div className="grid gap-4 sm:grid-cols-2"><AdminField label="رنگ متن" htmlFor="report-day-text-color" hint="خالی = سفید"><input id="report-day-text-color" type="color" value={draft.textColor || "#ffffff"} onChange={(event) => setDraft((value) => ({ ...value, textColor: event.target.value }))} className="h-10 w-full rounded-control border border-border bg-surface p-1" /></AdminField><AdminField label="رنگ پس‌زمینه" htmlFor="report-day-background-color" hint="خالی = مشکی"><input id="report-day-background-color" type="color" value={draft.backgroundColor || "#000000"} onChange={(event) => setDraft((value) => ({ ...value, backgroundColor: event.target.value }))} className="h-10 w-full rounded-control border border-border bg-surface p-1" /></AdminField></div><div className="flex items-center gap-3"><button type="button" disabled={busy} onClick={() => void save()} className="inline-flex min-h-10 items-center gap-2 rounded-control bg-brand px-4 text-xs font-black text-brand-foreground disabled:opacity-50"><Save className="h-4 w-4" />{busy ? "در حال ذخیره…" : "ذخیره"}</button>{message ? <span role="status" className="text-xs">{message}</span> : null}</div></div></section>
      <aside className="rounded-card border border-border bg-surface p-4"><h2 className="text-sm font-black">وضعیت روز انتخاب‌شده</h2><dl className="mt-4 space-y-3 text-xs"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">شماره شب</dt><dd className="font-black">{selected ? new Intl.NumberFormat("fa-IR").format(selected.nightNumber) : "—"}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">تعداد گزارش</dt><dd className="font-black">{selected ? new Intl.NumberFormat("fa-IR").format(selected.reportCount) : "—"}</dd></div></dl><p className="mt-5 text-[11px] leading-6 text-muted-foreground">با پاک‌کردن عنوان، زیرعنوان، توضیح و رنگ‌ها، تنظیمات روز حذف می‌شود؛ اما اگر گزارش داشته باشد همچنان در فهرست عمومی می‌ماند.</p></aside></div></div>;
}
