export type ContentCoverAttachment = {
  id: number;
  type?: string;
  url?: string;
  poster_url?: string | null;
  thumbnail_url?: string | null;
};

/**
 * Video posters are generated by the backend after processing the upload.
 * Never substitute an application illustration when that generated still is
 * unavailable: the video element can render without a poster.
 */
export function contentCover(
  attachments: ContentCoverAttachment[] | undefined,
  format?: string,
  primaryAttachmentId?: number,
): string | undefined {
  const primary = attachments?.find((attachment) => attachment.id === primaryAttachmentId);
  if (primary?.type === "image") return primary.url;

  if (format === "video") {
    const video = primary?.type === "video" ? primary : attachments?.find((attachment) => attachment.type === "video");
    return video?.poster_url || video?.thumbnail_url || undefined;
  }

  return attachments?.find((attachment) => attachment.type === "image")?.url;
}

/** First image written into a body, either HTML (`<img src>`) or Markdown (`![alt](url)`). */
export function firstBodyImage(body: string | undefined): string | undefined {
  if (!body) return undefined;
  const html = /<img\b[^>]*?\bsrc=["']([^"']+)["']/i.exec(body);
  const markdown = /!\[[^\]]*\]\(\s*<?([^)\s>]+)/.exec(body);
  const first = [html, markdown].filter((match): match is RegExpExecArray => Boolean(match)).sort((a, b) => a.index - b.index)[0];
  return first?.[1];
}
