export type ContentCoverAttachment = {
  id: number;
  type?: string;
  url?: string;
  poster_url?: string | null;
  thumbnail_url?: string | null;
};

/**
 * Video posters are generated by the backend after processing the upload.
 * Never substitute an application illustration when that generated still is
 * unavailable: the video element can render without a poster.
 */
export function contentCover(
  attachments: ContentCoverAttachment[] | undefined,
  format?: string,
): string | undefined {
  if (format === "video") {
    const video = attachments?.find((attachment) => attachment.type === "video");
    return video?.poster_url || video?.thumbnail_url || undefined;
  }

  return attachments?.find((attachment) => attachment.type === "image")?.url;
}
