import { FileText, Headphones, Image as ImageIcon, Play, Sparkles } from "lucide-react";
import type { ContentItem } from "../types";

type ContentCardProps = { item: ContentItem; onOpenPreview: () => void; };

const mediaIcons = { image: ImageIcon, audio: Headphones, document: FileText };

export function ContentCard({ item, onOpenPreview }: ContentCardProps) {
  const Icon = mediaIcons[item.media.kind];
  const hero = item.category === "featured";
  return <article className={"overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900/45 " + (hero ? "shadow-sm" : "")}>{hero ? <div className="relative min-h-48 bg-[radial-gradient(circle_at_80%_0%,rgba(239,68,68,.75),transparent_35%),linear-gradient(145deg,#1e293b,#020617)] p-5 text-white"><Sparkles className="h-6 w-6 text-amber-300" /><span className="mt-5 inline-flex rounded-md bg-brand-red px-2 py-1 text-[10px] font-black">{item.badge}</span><h2 className="mt-2 text-base font-black leading-7">{item.title}</h2><p className="mt-2 text-xs leading-6 text-slate-200">{item.subtitle}</p></div> : <div className="flex items-center gap-3 p-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-brand-red/10 text-brand-red"><Icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="text-[10px] font-bold text-slate-500">{item.author ?? item.subtitle}</p><h2 className="mt-1 text-sm font-black leading-6 text-slate-950 dark:text-white">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{item.media.duration ?? item.media.description}</p></div></div>}<div className="p-4 pt-3"><p className="text-xs leading-7 text-slate-600 dark:text-slate-300">{item.description}</p><button type="button" onClick={onOpenPreview} className="mt-4 inline-flex items-center gap-1.5 rounded-xl bg-slate-100 px-3 py-2 text-xs font-black text-slate-700 transition hover:bg-brand-red hover:text-white dark:bg-slate-800 dark:text-slate-200">{item.media.kind === "audio" ? <Play className="h-4 w-4 fill-current" /> : <Icon className="h-4 w-4" />}{item.media.kind === "document" ? "دریافت فیش" : item.media.kind === "audio" ? "پیش‌نمایش صوت" : "مشاهده محتوا"}</button></div></article>;
}