"use client";
import { useEffect, useMemo, useState } from "react";
import { getAllSquares, getCities, type SquareMarker } from "../services/map.service";
import type { City, MapStatus, Province } from "../types";
export type MapLevel = "country" | "province" | "city";
export type CountAggregate = { id: number; name: string; count: number; latitude: number; longitude: number };
function aggregate(items: SquareMarker[], key: "provinceId" | "cityId", nameKey: "provinceName" | "cityName"): CountAggregate[] {
  const grouped = new Map<number, CountAggregate & { lat: number; lng: number }>();
  for (const square of items) { const id = square[key]; if (!id) continue; const item = grouped.get(id) ?? { id, name: square[nameKey] || "محدوده", count: 0, latitude: 0, longitude: 0, lat: 0, lng: 0 }; item.count++; item.lat += square.latitude; item.lng += square.longitude; item.latitude = item.lat / item.count; item.longitude = item.lng / item.count; grouped.set(id, item); }
  return [...grouped.values()];
}
export function useMap() {
  const [provinces, setProvinces] = useState<Province[]>([]); const [provinceCities, setProvinceCities] = useState<City[]>([]); const [allSquares, setAllSquares] = useState<SquareMarker[]>([]); const [selectedProvinceId, setSelectedProvinceId] = useState(0); const [selectedCityId, setSelectedCityId] = useState(0); const [level, setLevel] = useState<MapLevel>("country"); const [provinceQuery, setProvinceQuery] = useState(""); const [cityQuery, setCityQuery] = useState(""); const [status, setStatus] = useState<MapStatus>("idle"); const [error, setError] = useState<string | null>(null);
  const selectedProvince = provinces.find((item) => item.id === selectedProvinceId); const selectedCity = provinceCities.find((item) => item.id === selectedCityId); const provinceAggregates = useMemo(() => aggregate(allSquares, "provinceId", "provinceName"), [allSquares]); const provinceSquares = useMemo(() => allSquares.filter((item) => item.provinceId === selectedProvinceId), [allSquares, selectedProvinceId]); const cityAggregates = useMemo(() => aggregate(provinceSquares, "cityId", "cityName"), [provinceSquares]); const citySquares = useMemo(() => provinceSquares.filter((item) => item.cityId === selectedCityId), [provinceSquares, selectedCityId]);
  useEffect(() => { let active = true; queueMicrotask(() => active && setStatus("loading")); void getAllSquares().then((items) => { if (!active) return; setAllSquares(items); const names = new Map<number, string>(); for (const item of items) if (item.provinceId && item.provinceName) names.set(item.provinceId, item.provinceName); setProvinces([...names].map(([id, name]) => ({ id, name }))); setStatus("ready"); }).catch(() => { if (active) { setError("دریافت میدان‌ها با خطا مواجه شد."); setStatus("error"); } }); return () => { active = false; }; }, []);
  useEffect(() => { if (!selectedProvinceId) { queueMicrotask(() => setProvinceCities([])); return; } void getCities(selectedProvinceId).then(setProvinceCities).catch(() => setProvinceCities([])); }, [selectedProvinceId]);
  const setViewportLevel = (next: MapLevel, center: { latitude: number; longitude: number }) => { if (next === "country") { setLevel(next); return; } if (!selectedProvinceId) { const closest = provinceAggregates.reduce<CountAggregate | null>((best, item) => !best || (item.latitude - center.latitude) ** 2 + (item.longitude - center.longitude) ** 2 < (best.latitude - center.latitude) ** 2 + (best.longitude - center.longitude) ** 2 ? item : best, null); if (closest) setSelectedProvinceId(closest.id); } if (next === "city" && !selectedCityId) { const closest = cityAggregates.reduce<CountAggregate | null>((best, item) => !best || (item.latitude - center.latitude) ** 2 + (item.longitude - center.longitude) ** 2 < (best.latitude - center.latitude) ** 2 + (best.longitude - center.longitude) ** 2 ? item : best, null); if (closest) setSelectedCityId(closest.id); } setLevel(next); };
  return { selectedProvince, selectedCity, selectedProvinceId, selectedCityId, provinceCities, visibleProvinces: provinces.filter((item) => item.name.includes(provinceQuery.trim())), visibleCities: provinceCities.filter((item) => item.name.includes(cityQuery.trim())), provinceQuery, cityQuery, level, provinceAggregates, cityAggregates, citySquares, status, error, activeCount: allSquares.length, selectProvince: (id: number) => { setSelectedProvinceId(id); setSelectedCityId(0); setCityQuery(""); setLevel("province"); }, selectCity: (id: number) => { setSelectedCityId(id); setLevel("city"); }, setViewportLevel, setProvinceQuery, setCityQuery };
}
